server:
  port: 8081

app:
  topic: twitter-topic
#  returnTopic: transaction_extorno


spring:
  application:
    name: kafka-twitter-consumer
  h2:
    console:
      enabled: true
      path: /h2
    datasource:
      url: jdbc:h2:file:~/test-consumer
      username:
      password:
      driverClassName: org.h2.Driver

#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQL94Dialect
#        temp:
#          use_jdbc_metadata_defaults: false
#    hibernate:
#      hibernate.ddl-auto: update
#      generate-ddl: true
#      show-sql: true
#  datasource:
#    driverClassName: org.postgresql.Driver
#    url: jdbc:postgresql://34.71.73.122:5432/limites
#    username: keycloak
#    password: password

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: tweet-grupo-1
      key-serializer: org.apache.kafka.common.serialization.StringDeserializer
      value-serializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      enable-auto-commit:  true

    properties:
      isolation:
        level: read_committed



